default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: docker
  host: 127.0.0.1

development:
  <<: *default
  database: blog_with_nested_articles_development


test:
  <<: *default
  database: blog_with_nested_articles_test
